[2024-02-26T15:48:19.810+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: yearly.Send_to_bq manual__2024-02-26T15:42:19.610221+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
