[2024-02-28T07:59:43.331+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: hourly.Get_stockinfo_hourly scheduled__2024-02-27T04:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
